package com.spotshare.reservation;

import java.time.OffsetDateTime;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import com.spotshare.parking.ParkingSpace;
import com.spotshare.user.User;

/**
 * One driver's booking of a parking space for the half-open period
 * {@code [arrival, departure)}. Adjacent reservations (one ends exactly when
 * the next starts) are allowed; overlapping CONFIRMED reservations for the
 * same space are impossible — the {@code excl_reservations_no_overlap}
 * exclusion constraint (Flyway V4) rejects them at the database level, and
 * the application serializes bookings per space with an advisory lock
 * (spec §9).
 *
 * <p>Money is integer cents: {@code hourlyRateCents} snapshots the share
 * window's price at booking time ({@code null} = free share) and
 * {@code totalCents} is the prorated total, computed once and stored.
 * There is no payment in V1 — every reservation is "Beta — no payment
 * required".
 *
 * <p>The {@code period} tstzrange column is generated by the database and
 * is deliberately not mapped here; Hibernate never writes it.
 */
@Entity
@Table(name = "reservations")
public class Reservation {

    @Id
    // Assigned in Java so the id is stable from construction.
    private UUID id = UUID.randomUUID();

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "space_id", nullable = false)
    private ParkingSpace space;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "driver_id", nullable = false)
    private User driver;

    @Column(name = "arrival", nullable = false)
    private OffsetDateTime arrival;

    @Column(name = "departure", nullable = false)
    private OffsetDateTime departure;

    /** Snapshot of the window's hourly price in cents; null = free share. */
    @Column(name = "hourly_rate_cents")
    private Integer hourlyRateCents;

    /** Prorated total in cents, computed at booking time. */
    @Column(name = "total_cents", nullable = false)
    private int totalCents;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private ReservationStatus status;

    /** Public code, e.g. "SP-K84D2" — shown to the driver, unique. */
    @Column(nullable = false, length = 8, unique = true)
    private String code;

    /**
     * Client-supplied idempotency key, scoped per driver. A repeat POST with
     * the same key returns the original reservation instead of a duplicate.
     */
    @Column(name = "idempotency_key", length = 64)
    private String idempotencyKey;

    @Column(name = "cancelled_at")
    private OffsetDateTime cancelledAt;

    @Enumerated(EnumType.STRING)
    @Column(name = "cancelled_by", length = 16)
    private CancelledBy cancelledBy;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    protected Reservation() {
        // JPA
    }

    public Reservation(ParkingSpace space, User driver,
                       OffsetDateTime arrival, OffsetDateTime departure,
                       Integer hourlyRateCents, int totalCents,
                       String code, String idempotencyKey,
                       OffsetDateTime createdAt) {
        this.space = space;
        this.driver = driver;
        this.arrival = arrival;
        this.departure = departure;
        this.hourlyRateCents = hourlyRateCents;
        this.totalCents = totalCents;
        this.status = ReservationStatus.CONFIRMED;
        this.code = code;
        this.idempotencyKey = idempotencyKey;
        this.createdAt = createdAt;
        this.updatedAt = createdAt;
    }

    public UUID getId() {
        return id;
    }

    public ParkingSpace getSpace() {
        return space;
    }

    public User getDriver() {
        return driver;
    }

    public OffsetDateTime getArrival() {
        return arrival;
    }

    public OffsetDateTime getDeparture() {
        return departure;
    }

    public Integer getHourlyRateCents() {
        return hourlyRateCents;
    }

    public int getTotalCents() {
        return totalCents;
    }

    public ReservationStatus getStatus() {
        return status;
    }

    public String getCode() {
        return code;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    public OffsetDateTime getCancelledAt() {
        return cancelledAt;
    }

    public CancelledBy getCancelledBy() {
        return cancelledBy;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    /** Driver cancellation: releases the period; the record is kept for history. */
    public void cancel(OffsetDateTime now, CancelledBy by) {
        this.status = ReservationStatus.CANCELLED;
        this.cancelledAt = now;
        this.cancelledBy = by;
        this.updatedAt = now;
    }
}
